hash-format = "sha256"

[[files]]
file = "mods/configured.pw.toml"
hash = "e1652216456cb6c5026b3e6b48d98b1509457eb6d974e18002af4ec3bf040ffa"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "03c4f9a926fc9bd90fc98c6dac2a39e70b28303e4f3519756a7b246444548654"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d056f638b4ade16a2f5d2562c5f1332a8d09c69974b4dad6582b92d93329e7e9"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "5f55a318ed9bc3b1db89fc4b5315bfe98d691a6ed75cdd49ca075da52bc6826a"
metafile = true

[[files]]
file = "mods/esf-entity-sound-features.pw.toml"
hash = "1dd87ea53e292e9817bde805d03c1e26ff276f6b1fd9e0291a91d1cbc76e1e43"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "6a2693aaab21ce7c32b958b81ee5e9cad0d014cdf68c067049b2fc652159d9d1"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "e34877bf9d74d3f71c69fdd47ce509fa473fadcdf88f87f79754a522cfa1c60b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "e5a88eeea38105e024dc8c8849e28d90af25cec68f1d0f6716796fe9746bddd2"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "03d264a85c6b6fd0f011c958caf94a3238931fdd48c5c156ddb6e13fc16ce601"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "40e1fdc8c58f72bb947b978a773cf963b2d28bb49832500c2bd886f7ac6629bb"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f3c75c6d415e4d68307d972ed30ced99ba05968c7ff85301154a60fc42eeed95"
metafile = true

[[files]]
file = "resourcepacks/create-lootr.pw.toml"
hash = "5736ae114ce1c28bf4b03cf8228277758c08be8bbb2caa7d0977c9b1020603bc"
metafile = true

[[files]]
file = "resourcepacks/create-sophisticated-backpacks.pw.toml"
hash = "9894340781fca02078877ff3ee942b1a66e5387aedab8a0d99ab69f4904cf0c5"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "3742efd536b417560395d9aab9643e2a97c105a60fd7f37c9a825024c7479359"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "72b919a0242253a1540a0fa424ea5a652787365186ac9f5fa5a67583bb5d368c"
metafile = true

[[files]]
file = "resourcepacks/fresh-moves.pw.toml"
hash = "d22bff8a4ecb807d779784716ad315466778d0457b0d734eeeb6ff7f5a296a3f"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-glass.pw.toml"
hash = "9558758e85c4d4e25da6c62d2381e24de2794f1307136ee9b4be98ed32baf6ad"
metafile = true

[[files]]
file = "resourcepacks/icons.pw.toml"
hash = "61a4566505db6e39003776e8035c7535cee9fc8091514040dfadf02580eb0fe4"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-add-ons.pw.toml"
hash = "0eee40180a90d6616be68d87236b3ce7eda3ed1c747615356fc65b2681981c29"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "c3c618df6fa8e9f4b8de628c050cde77fec5fac7778a38ac94b28f42183e3a2a"
metafile = true

[[files]]
file = "resourcepacks/soft-weather.pw.toml"
hash = "a76052f76e4eeb7f6114f3bad62fc1e967b8f39425bfb1e369c2ead7d56519b0"
metafile = true
