hash-format = "sha256"

[[files]]
file = "mods/configured.pw.toml"
hash = "e1652216456cb6c5026b3e6b48d98b1509457eb6d974e18002af4ec3bf040ffa"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "03c4f9a926fc9bd90fc98c6dac2a39e70b28303e4f3519756a7b246444548654"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d056f638b4ade16a2f5d2562c5f1332a8d09c69974b4dad6582b92d93329e7e9"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "5f55a318ed9bc3b1db89fc4b5315bfe98d691a6ed75cdd49ca075da52bc6826a"
metafile = true

[[files]]
file = "mods/esf-entity-sound-features.pw.toml"
hash = "1dd87ea53e292e9817bde805d03c1e26ff276f6b1fd9e0291a91d1cbc76e1e43"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "6a2693aaab21ce7c32b958b81ee5e9cad0d014cdf68c067049b2fc652159d9d1"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "e34877bf9d74d3f71c69fdd47ce509fa473fadcdf88f87f79754a522cfa1c60b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "e5a88eeea38105e024dc8c8849e28d90af25cec68f1d0f6716796fe9746bddd2"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "03d264a85c6b6fd0f011c958caf94a3238931fdd48c5c156ddb6e13fc16ce601"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "40e1fdc8c58f72bb947b978a773cf963b2d28bb49832500c2bd886f7ac6629bb"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f3c75c6d415e4d68307d972ed30ced99ba05968c7ff85301154a60fc42eeed95"
metafile = true

[[files]]
file = "resourcepacks/create-lootr.pw.toml"
hash = "6774d90dd525b77c08814f8cdeaaa5fdf2d4dc265d45c9a7a3bfcd2da2494981"
metafile = true

[[files]]
file = "resourcepacks/create-sophisticated-backpacks.pw.toml"
hash = "5af5f0e483f294ad7db881e4a42fc27959929f748c6e8a4079dce047b7b08c8a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "dd6929c4e38eeb90105d587a36352365bf1e297a37207720e2ab95304f1887fa"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "6a361be792283eb0dc65c8c4bb39c1c41cc9d959f167e7306bdf559a171c967d"
metafile = true

[[files]]
file = "resourcepacks/fresh-moves.pw.toml"
hash = "125d893daa0b0f57a39f3f295344223681201b45020ff83e39540766c982e769"
metafile = true

[[files]]
file = "resourcepacks/fusion-3d-items.pw.toml"
hash = "d86229049d870034cea564802dbada9246fac5f6773332e594c9e477a05bbfb7"
metafile = true

[[files]]
file = "resourcepacks/fusion-block-transitions.pw.toml"
hash = "3d5152df2501abf43532d7d3428c07090082cbbe5893a0d174caceff5ee9f7a0"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-blocks.pw.toml"
hash = "d3c9542ee04fc53ce47fe4eb3859af84b0514a34d9798d91b001b3b7d683196b"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-glass.pw.toml"
hash = "b5adc604f7875ced2804536228739046b56ec384d46bd31077025ed4ab21c528"
metafile = true

[[files]]
file = "resourcepacks/fusion-emissive-ores.pw.toml"
hash = "799f1b20d340e66837ccd5bcba2a1fc9bd4567c403a664d4087c8c7bd6a98061"
metafile = true

[[files]]
file = "resourcepacks/fusion-stacking-items.pw.toml"
hash = "734593f3f25cd9539f4455cb72deadb13e18afeb7ed6fc261a7892974371b0d9"
metafile = true

[[files]]
file = "resourcepacks/icons.pw.toml"
hash = "f2d9fa4914c0eefcc1be552cf1362ce255962a16ece14916a6bf2ad70e76b281"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-add-ons.pw.toml"
hash = "d4da54574446fa7fcdf4f50c02c216a740ba8550eb9d76cf086a33fb70d69522"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "2c07e15405dab1b132cd6fe3713ee821e693b20db0a465bc3c7ba7a6442b0feb"
metafile = true

[[files]]
file = "resourcepacks/soft-weather.pw.toml"
hash = "174a0d836cbf584636001deab3291ddf64e9dacbc2644ed8aa843248bc175d1e"
metafile = true
