hash-format = "sha256"

[[files]]
file = "mods/configured.pw.toml"
hash = "af4dc4828902eae1784568632a749fe9a442943f1570ac0ba3ea75e79934be41"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "381a26678e6812b162d9524c4e1a5a952d70ec9ababae81e09bba1ef21b61cdc"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "1c425a8664e738632620b09ae9f2245a77133e15b25462eee61a7d794d518e78"
metafile = true

[[files]]
file = "mods/esf-entity-sound-features.pw.toml"
hash = "56b7d8b533d28f68cbaf1b0bd56ef41f35cefbf6f2868af8d090dc91b3ceecba"
metafile = true
