name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "285b87faaedb541bc6a9b4a7fd62786d6397e3f857fa38a3ef8248b757cea4f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
