name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12577b702f69ab798414b4dc643e3dcd3a31701ae5157235416e71328b0b1946"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
