name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3bc868d2b3864ef1edc036ebad25dc6125b5377195e8dc492189062de3ac5a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
