name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44df26488085d48bb544c2306a1d2cb7fd028fe187c8defa522b38ec0b4ab018"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
