name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "459ca03ab61fffa92a69a2f97943b50ba57cf17cd46fadaa4c8807e89562fa4b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
