name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8a77179fed549adb463a0b10054e96931fd0f7319392b30fe97b069a8eaa283"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
