name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "673cbc592587356d7d0ed3a0357eebf3e74c0c4284a810af51d4bc48987c86cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
