name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a16e1a847a2ed4451590be9f43dfbe0d004e592392c216b7d190b69df955ee1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
