name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
recommended-ram = "6144"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db2ae87c76531e5da9c42c894e6d60a068eac6867338d9fdb4c193ccec798e14"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
