name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71e258ac480e4f6695bac5249639b49a789327a8e51ad824b3b71f44d380d21b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
