name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c3cabf132190b800fa25c203620b5e4d0f34cdb0aa39953e1e8d393c6cea41e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
